version: '3.8'

services:
  app:
    build: .
    image: yevhendanylchenko/clinic:latest
    container_name: clinic
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - APP_PORT=80
    volumes:
      - ./config:/app/config
    command: npm start dev -- --host